
services:

  db:
    image: postgres:17-alpine
    container_name: inventory-db

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: inventory-backend

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"
    
    restart: always

    depends_on:
      - db

  frontend:
    build:
      context: ./frontend

    container_name: inventory-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

volumes:
  postgres_data: